CREATE TABLE IF NOT EXISTS products(
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()

);